use crate::frontend::ast::{Expr, LiteralValue, Stmt, SwitchCase};
use crate::frontend::token::TokenType;

pub fn transpile_to_js(stmts: &[Stmt]) -> String {
    let mut js = String::new();
    js.push_str("// Generated by Eronom Transpiler\n\n");
    let indent = 0;
    for stmt in stmts {
        emit_stmt(&mut js, stmt, indent);
    }
    js
}

fn emit_indent(out: &mut String, indent: usize) {
    for _ in 0..indent {
        out.push_str("    ");
    }
}

fn emit_stmt(out: &mut String, stmt: &Stmt, indent: usize) {
    match stmt {
        Stmt::TypeAlias(_, _, _, _) | Stmt::Interface(_, _, _, _) => {
            // Type annotations and interfaces are completely erased in JavaScript output
        }
        Stmt::Enum(name, variants, _) => {
            emit_indent(out, indent);
            out.push_str(&format!("const {} = Object.freeze({{\n", name));
            let mut next_auto_val: f64 = 0.0;
            let mut computed_variants = Vec::new();

            for (v_name, v_val) in variants {
                let val_str = match v_val {
                    Some(LiteralValue::Number(n)) => {
                        next_auto_val = n + 1.0;
                        n.to_string()
                    }
                    Some(LiteralValue::String(s)) => {
                        serde_json::to_string(s).unwrap_or_else(|_| format!("\"{}\"", s))
                    }
                    Some(LiteralValue::Boolean(b)) => b.to_string(),
                    Some(LiteralValue::Null) => "null".to_string(),
                    None => {
                        let current = next_auto_val;
                        next_auto_val += 1.0;
                        current.to_string()
                    }
                };
                computed_variants.push((v_name.clone(), val_str));
            }

            for (v_name, v_val) in &computed_variants {
                emit_indent(out, indent + 1);
                out.push_str(&format!("{}: {},\n", v_name, v_val));
            }

            // Numeric reverse mapping
            for (v_name, v_val) in &computed_variants {
                if v_val.parse::<f64>().is_ok() {
                    emit_indent(out, indent + 1);
                    out.push_str(&format!("[{}]: \"{}\",\n", v_val, v_name));
                }
            }

            emit_indent(out, indent);
            out.push_str("});\n\n");
        }
        Stmt::Struct(name, composed, _fields, methods, _) => {
            emit_indent(out, indent);
            let extends_clause = if let Some(parent) = composed.first() {
                format!(" extends {}", parent)
            } else {
                String::new()
            };
            out.push_str(&format!("class {}{} {{\n", name, extends_clause));

            // Constructor
            emit_indent(out, indent + 1);
            out.push_str("constructor(init = {}) {\n");
            if !composed.is_empty() {
                emit_indent(out, indent + 2);
                out.push_str("super(init);\n");
            }
            emit_indent(out, indent + 2);
            out.push_str("Object.assign(this, init);\n");
            emit_indent(out, indent + 1);
            out.push_str("}\n");

            // Methods
            for (m_name, m_params, m_body) in methods {
                emit_indent(out, indent + 1);
                out.push_str(&format!("{}({}) ", m_name, m_params.join(", ")));
                emit_stmt_inline(out, m_body, indent + 1);
                out.push('\n');
            }

            emit_indent(out, indent);
            out.push_str("}\n\n");
        }
        Stmt::VarDecl(name, _, is_const, expr, _) => {
            // Check if it's a top-level named function declaration: fn name(...) { ... }
            if let Expr::Function(params, _, body) = expr {
                emit_indent(out, indent);
                let param_names: Vec<&str> = params.iter().map(|p| p.name.as_str()).collect();
                out.push_str(&format!("function {}({}) ", name, param_names.join(", ")));
                emit_stmt_inline(out, body, indent);
                out.push('\n');
                return;
            }

            emit_indent(out, indent);
            let kw = if *is_const { "const" } else { "let" };
            out.push_str(&format!("{} {} = {};\n", kw, name, emit_expr(expr)));
        }
        Stmt::Expr(expr) => {
            emit_indent(out, indent);
            out.push_str(&format!("{};\n", emit_expr(expr)));
        }
        Stmt::Print(expr) => {
            emit_indent(out, indent);
            out.push_str(&format!("console.log({});\n", emit_expr(expr)));
        }
        Stmt::Block(stmts) => {
            emit_indent(out, indent);
            out.push_str("{\n");
            for s in stmts {
                emit_stmt(out, s, indent + 1);
            }
            emit_indent(out, indent);
            out.push_str("}\n");
        }
        Stmt::If(cond, then_b, else_b) => {
            emit_indent(out, indent);
            out.push_str(&format!("if ({}) ", emit_expr(cond)));
            emit_stmt_inline(out, then_b, indent);
            if let Some(else_stmt) = else_b {
                out.push_str(" else ");
                emit_stmt_inline(out, else_stmt, indent);
            }
            out.push('\n');
        }
        Stmt::While(cond, body) => {
            emit_indent(out, indent);
            out.push_str(&format!("while ({}) ", emit_expr(cond)));
            emit_stmt_inline(out, body, indent);
            out.push('\n');
        }
        Stmt::For(var_name, start, end, body) => {
            emit_indent(out, indent);
            out.push_str(&format!(
                "for (let {} = {}; {} <= {}; {}++) ",
                var_name,
                emit_expr(start),
                var_name,
                emit_expr(end),
                var_name
            ));
            emit_stmt_inline(out, body, indent);
            out.push('\n');
        }
        Stmt::ForIn(var_name, iter, body) => {
            emit_indent(out, indent);
            out.push_str(&format!("for (const {} of {}) ", var_name, emit_expr(iter)));
            emit_stmt_inline(out, body, indent);
            out.push('\n');
        }
        Stmt::Break => {
            emit_indent(out, indent);
            out.push_str("break;\n");
        }
        Stmt::Continue => {
            emit_indent(out, indent);
            out.push_str("continue;\n");
        }
        Stmt::Throw(expr) => {
            emit_indent(out, indent);
            out.push_str(&format!("throw {};\n", emit_expr(expr)));
        }
        Stmt::Try(try_body, catch_clause, finally_body) => {
            emit_indent(out, indent);
            out.push_str("try ");
            emit_stmt_inline(out, try_body, indent);
            if let Some((param, catch_b)) = catch_clause {
                out.push_str(&format!(" catch ({}) ", param));
                emit_stmt_inline(out, catch_b, indent);
            }
            if let Some(finally_b) = finally_body {
                out.push_str(" finally ");
                emit_stmt_inline(out, finally_b, indent);
            }
            out.push('\n');
        }
        Stmt::Return(expr_opt, _) => {
            emit_indent(out, indent);
            if let Some(e) = expr_opt {
                out.push_str(&format!("return {};\n", emit_expr(e)));
            } else {
                out.push_str("return;\n");
            }
        }
        Stmt::Switch(target, cases, default_body) => {
            emit_indent(out, indent);
            out.push_str(&format!("switch ({}) {{\n", emit_expr(target)));
            for case in cases {
                for v in &case.values {
                    emit_indent(out, indent + 1);
                    out.push_str(&format!("case {}:\n", emit_expr(v)));
                }
                emit_stmt(out, &case.body, indent + 2);
                emit_indent(out, indent + 2);
                out.push_str("break;\n");
            }
            if let Some(def) = default_body {
                emit_indent(out, indent + 1);
                out.push_str("default:\n");
                emit_stmt(out, def, indent + 2);
            }
            emit_indent(out, indent);
            out.push_str("}\n");
        }
        Stmt::Import(names, path) => {
            emit_indent(out, indent);
            let js_path = if path.ends_with(".er") {
                format!("{}.js", &path[..path.len() - 3])
            } else {
                path.clone()
            };
            out.push_str(&format!(
                "import {{ {} }} from \"{}\";\n",
                names.join(", "),
                js_path
            ));
        }
        Stmt::Export(inner) => {
            emit_indent(out, indent);
            out.push_str("export ");
            let mut inner_str = String::new();
            emit_stmt(&mut inner_str, inner, 0);
            out.push_str(inner_str.trim_start());
        }
        Stmt::Concurrent(body) => {
            emit_stmt(out, body, indent);
        }
    }
}

fn emit_stmt_inline(out: &mut String, stmt: &Stmt, indent: usize) {
    match stmt {
        Stmt::Block(stmts) => {
            out.push_str("{\n");
            for s in stmts {
                emit_stmt(out, s, indent + 1);
            }
            emit_indent(out, indent);
            out.push('}');
        }
        other => {
            out.push_str("{\n");
            emit_stmt(out, other, indent + 1);
            emit_indent(out, indent);
            out.push('}');
        }
    }
}

pub fn emit_expr(expr: &Expr) -> String {
    match expr {
        Expr::Literal(val) => match val {
            LiteralValue::Number(n) => n.to_string(),
            LiteralValue::String(s) => serde_json::to_string(s).unwrap_or_else(|_| format!("\"{}\"", s)),
            LiteralValue::Boolean(b) => b.to_string(),
            LiteralValue::Null => "null".to_string(),
        },
        Expr::Variable(name, _) => name.clone(),
        Expr::Assign(name, val, _) => format!("({} = {})", name, emit_expr(val)),
        Expr::Binary(left, op, right) => {
            let op_str = match op {
                TokenType::Plus => "+",
                TokenType::Minus => "-",
                TokenType::Star => "*",
                TokenType::Slash => "/",
                TokenType::Percent => "%",
                TokenType::EqualEqual => "===",
                TokenType::BangEqual => "!==",
                TokenType::Less => "<",
                TokenType::LessEqual => "<=",
                TokenType::Greater => ">",
                TokenType::GreaterEqual => ">=",
                TokenType::Ampersand => "&",
                TokenType::Pipe => "|",
                TokenType::Caret => "^",
                TokenType::LessLess => "<<",
                TokenType::GreaterGreater => ">>",
                _ => "+",
            };
            format!("({} {} {})", emit_expr(left), op_str, emit_expr(right))
        }
        Expr::Logical(left, op, right) => {
            let op_str = match op {
                TokenType::And => "&&",
                TokenType::Or => "||",
                _ => "&&",
            };
            format!("({} {} {})", emit_expr(left), op_str, emit_expr(right))
        }
        Expr::Unary(op, operand) => {
            let op_str = match op {
                TokenType::Bang => "!",
                TokenType::Minus => "-",
                TokenType::Typeof => "typeof ",
                TokenType::Tilde => "~",
                _ => "",
            };
            format!("({}{})", op_str, emit_expr(operand))
        }
        Expr::Prefix(op, operand) => {
            let op_str = match op {
                TokenType::PlusPlus => "++",
                TokenType::MinusMinus => "--",
                _ => "",
            };
            format!("({}{})", op_str, emit_expr(operand))
        }
        Expr::Postfix(op, operand) => {
            let op_str = match op {
                TokenType::PlusPlus => "++",
                TokenType::MinusMinus => "--",
                _ => "",
            };
            format!("({}{})", emit_expr(operand), op_str)
        }
        Expr::Ternary(cond, then_b, else_b) => {
            format!(
                "({} ? {} : {})",
                emit_expr(cond),
                emit_expr(then_b),
                emit_expr(else_b)
            )
        }
        Expr::Call(callee, args) => {
            let args_str = args.iter().map(emit_expr).collect::<Vec<_>>().join(", ");
            if let Expr::Variable(name, _) = &**callee {
                if name == "print" {
                    return format!("console.log({})", args_str);
                }
            }
            format!("{}({})", emit_expr(callee), args_str)
        }
        Expr::Get(obj, prop) => format!("{}.{}", emit_expr(obj), prop),
        Expr::Set(obj, prop, val) => format!("({}.{} = {})", emit_expr(obj), prop, emit_expr(val)),
        Expr::Array(items) => {
            let items_str = items.iter().map(emit_expr).collect::<Vec<_>>().join(", ");
            format!("[{}]", items_str)
        }
        Expr::Object(pairs) => {
            let pairs_str = pairs
                .iter()
                .map(|(k, v)| format!("{}: {}", k, emit_expr(v)))
                .collect::<Vec<_>>()
                .join(", ");
            format!("{{ {} }}", pairs_str)
        }
        Expr::Function(params, _, body) => {
            let param_names: Vec<&str> = params.iter().map(|p| p.name.as_str()).collect();
            let mut body_str = String::new();
            emit_stmt_inline(&mut body_str, body, 0);
            format!("({}) => {}", param_names.join(", "), body_str)
        }
        Expr::GetIndex(obj, idx) => format!("{}[{}]", emit_expr(obj), emit_expr(idx)),
        Expr::SetIndex(obj, idx, val) => {
            format!("({}[{}] = {})", emit_expr(obj), emit_expr(idx), emit_expr(val))
        }
        Expr::StructInst(name, pairs, _) => {
            let pairs_str = pairs
                .iter()
                .map(|(k, v)| format!("{}: {}", k, emit_expr(v)))
                .collect::<Vec<_>>()
                .join(", ");
            format!("new {}({{ {} }})", name, pairs_str)
        }
        Expr::TypeCast(inner, _, _) => emit_expr(inner),
        Expr::Spawn(inner) => format!("Promise.resolve().then(() => {})", emit_expr(inner)),
    }
}

pub fn transform_expr_reactivity(expr: &Expr, state_vars: &[String], shadowed: &[String]) -> Expr {
    match expr {
        Expr::Literal(_) => expr.clone(),
        Expr::Variable(name, loc) => {
            if state_vars.contains(name) && !shadowed.contains(name) {
                Expr::Get(Box::new(Expr::Variable(name.clone(), loc.clone())), "value".to_string())
            } else {
                expr.clone()
            }
        }
        Expr::Assign(name, val, loc) => {
            let new_val = transform_expr_reactivity(val, state_vars, shadowed);
            if state_vars.contains(name) && !shadowed.contains(name) {
                Expr::Set(
                    Box::new(Expr::Variable(name.clone(), loc.clone())),
                    "value".to_string(),
                    Box::new(new_val),
                )
            } else {
                Expr::Assign(name.clone(), Box::new(new_val), loc.clone())
            }
        }
        Expr::Binary(left, op, right) => {
            Expr::Binary(
                Box::new(transform_expr_reactivity(left, state_vars, shadowed)),
                op.clone(),
                Box::new(transform_expr_reactivity(right, state_vars, shadowed)),
            )
        }
        Expr::Logical(left, op, right) => {
            Expr::Logical(
                Box::new(transform_expr_reactivity(left, state_vars, shadowed)),
                op.clone(),
                Box::new(transform_expr_reactivity(right, state_vars, shadowed)),
            )
        }
        Expr::Unary(op, operand) => {
            Expr::Unary(
                op.clone(),
                Box::new(transform_expr_reactivity(operand, state_vars, shadowed)),
            )
        }
        Expr::Prefix(op, operand) => {
            Expr::Prefix(
                op.clone(),
                Box::new(transform_expr_reactivity(operand, state_vars, shadowed)),
            )
        }
        Expr::Postfix(op, operand) => {
            Expr::Postfix(
                op.clone(),
                Box::new(transform_expr_reactivity(operand, state_vars, shadowed)),
            )
        }
        Expr::Ternary(cond, then_b, else_b) => {
            Expr::Ternary(
                Box::new(transform_expr_reactivity(cond, state_vars, shadowed)),
                Box::new(transform_expr_reactivity(then_b, state_vars, shadowed)),
                Box::new(transform_expr_reactivity(else_b, state_vars, shadowed)),
            )
        }
        Expr::Call(callee, args) => {
            Expr::Call(
                Box::new(transform_expr_reactivity(callee, state_vars, shadowed)),
                args.iter().map(|a| transform_expr_reactivity(a, state_vars, shadowed)).collect(),
            )
        }
        Expr::Get(obj, prop) => {
            if prop == "value" {
                if let Expr::Variable(name, _) = &**obj {
                    if state_vars.contains(name) {
                        return expr.clone();
                    }
                }
            }
            Expr::Get(
                Box::new(transform_expr_reactivity(obj, state_vars, shadowed)),
                prop.clone(),
            )
        }
        Expr::Set(obj, prop, val) => {
            Expr::Set(
                Box::new(transform_expr_reactivity(obj, state_vars, shadowed)),
                prop.clone(),
                Box::new(transform_expr_reactivity(val, state_vars, shadowed)),
            )
        }
        Expr::Array(items) => {
            Expr::Array(items.iter().map(|it| transform_expr_reactivity(it, state_vars, shadowed)).collect())
        }
        Expr::Object(pairs) => {
            Expr::Object(
                pairs
                    .iter()
                    .map(|(k, v)| (k.clone(), transform_expr_reactivity(v, state_vars, shadowed)))
                    .collect(),
            )
        }
        Expr::Function(params, ret_type, body) => {
            let mut new_shadowed = shadowed.to_vec();
            for p in params {
                new_shadowed.push(p.name.clone());
            }
            let new_body = transform_stmt_reactivity(body, state_vars, &new_shadowed);
            Expr::Function(params.clone(), ret_type.clone(), Box::new(new_body))
        }
        Expr::GetIndex(obj, idx) => {
            Expr::GetIndex(
                Box::new(transform_expr_reactivity(obj, state_vars, shadowed)),
                Box::new(transform_expr_reactivity(idx, state_vars, shadowed)),
            )
        }
        Expr::SetIndex(obj, idx, val) => {
            Expr::SetIndex(
                Box::new(transform_expr_reactivity(obj, state_vars, shadowed)),
                Box::new(transform_expr_reactivity(idx, state_vars, shadowed)),
                Box::new(transform_expr_reactivity(val, state_vars, shadowed)),
            )
        }
        Expr::StructInst(name, pairs, loc) => {
            Expr::StructInst(
                name.clone(),
                pairs
                    .iter()
                    .map(|(k, v)| (k.clone(), transform_expr_reactivity(v, state_vars, shadowed)))
                    .collect(),
                loc.clone(),
            )
        }
        Expr::TypeCast(inner, ty, loc) => {
            Expr::TypeCast(
                Box::new(transform_expr_reactivity(inner, state_vars, shadowed)),
                ty.clone(),
                loc.clone(),
            )
        }
        Expr::Spawn(inner) => {
            Expr::Spawn(Box::new(transform_expr_reactivity(inner, state_vars, shadowed)))
        }
    }
}

pub fn transform_stmt_reactivity(stmt: &Stmt, state_vars: &[String], shadowed: &[String]) -> Stmt {
    match stmt {
        Stmt::Expr(e) => Stmt::Expr(transform_expr_reactivity(e, state_vars, shadowed)),
        Stmt::Print(e) => Stmt::Print(transform_expr_reactivity(e, state_vars, shadowed)),
        Stmt::Block(stmts) => {
            let mut current_shadowed = shadowed.to_vec();
            let mut new_stmts = Vec::new();
            for s in stmts {
                new_stmts.push(transform_stmt_reactivity(s, state_vars, &current_shadowed));
                if let Stmt::VarDecl(name, _, _, _, _) = s {
                    current_shadowed.push(name.clone());
                }
            }
            Stmt::Block(new_stmts)
        }
        Stmt::VarDecl(name, ty, is_const, expr, loc) => {
            let new_expr = transform_expr_reactivity(expr, state_vars, shadowed);
            Stmt::VarDecl(name.clone(), ty.clone(), *is_const, new_expr, loc.clone())
        }
        Stmt::If(cond, then_b, else_b) => {
            Stmt::If(
                transform_expr_reactivity(cond, state_vars, shadowed),
                Box::new(transform_stmt_reactivity(then_b, state_vars, shadowed)),
                else_b
                    .as_ref()
                    .map(|b| Box::new(transform_stmt_reactivity(b, state_vars, shadowed))),
            )
        }
        Stmt::While(cond, body) => {
            Stmt::While(
                transform_expr_reactivity(cond, state_vars, shadowed),
                Box::new(transform_stmt_reactivity(body, state_vars, shadowed)),
            )
        }
        Stmt::For(var_name, start, end, body) => {
            let mut new_shadowed = shadowed.to_vec();
            new_shadowed.push(var_name.clone());
            Stmt::For(
                var_name.clone(),
                transform_expr_reactivity(start, state_vars, shadowed),
                transform_expr_reactivity(end, state_vars, shadowed),
                Box::new(transform_stmt_reactivity(body, state_vars, &new_shadowed)),
            )
        }
        Stmt::ForIn(var_name, iter, body) => {
            let mut new_shadowed = shadowed.to_vec();
            new_shadowed.push(var_name.clone());
            Stmt::ForIn(
                var_name.clone(),
                transform_expr_reactivity(iter, state_vars, shadowed),
                Box::new(transform_stmt_reactivity(body, state_vars, &new_shadowed)),
            )
        }
        Stmt::Return(expr_opt, loc) => {
            Stmt::Return(
                expr_opt
                    .as_ref()
                    .map(|e| transform_expr_reactivity(e, state_vars, shadowed)),
                loc.clone(),
            )
        }
        Stmt::Throw(e) => Stmt::Throw(transform_expr_reactivity(e, state_vars, shadowed)),
        Stmt::Try(try_b, catch_clause, fin_b) => {
            let new_catch = catch_clause.as_ref().map(|(param, b)| {
                let mut new_shadowed = shadowed.to_vec();
                new_shadowed.push(param.clone());
                (
                    param.clone(),
                    Box::new(transform_stmt_reactivity(b, state_vars, &new_shadowed)),
                )
            });
            Stmt::Try(
                Box::new(transform_stmt_reactivity(try_b, state_vars, shadowed)),
                new_catch,
                fin_b
                    .as_ref()
                    .map(|b| Box::new(transform_stmt_reactivity(b, state_vars, shadowed))),
            )
        }
        Stmt::Switch(target, cases, default_body) => {
            let new_target = transform_expr_reactivity(target, state_vars, shadowed);
            let new_cases = cases
                .iter()
                .map(|c| SwitchCase {
                    values: c
                        .values
                        .iter()
                        .map(|v| transform_expr_reactivity(v, state_vars, shadowed))
                        .collect(),
                    body: Box::new(transform_stmt_reactivity(&c.body, state_vars, shadowed)),
                })
                .collect();
            let new_default = default_body
                .as_ref()
                .map(|b| Box::new(transform_stmt_reactivity(b, state_vars, shadowed)));
            Stmt::Switch(new_target, new_cases, new_default)
        }
        Stmt::Export(s) => {
            Stmt::Export(Box::new(transform_stmt_reactivity(s, state_vars, shadowed)))
        }
        Stmt::Concurrent(s) => {
            Stmt::Concurrent(Box::new(transform_stmt_reactivity(s, state_vars, shadowed)))
        }
        other => other.clone(),
    }
}

pub fn transpile_expr_reactivity(expr_str: &str, state_vars: &[String]) -> Option<String> {
    let trimmed = expr_str.trim().trim_end_matches(';').trim();
    if trimmed.is_empty() {
        return None;
    }
    let tokens = crate::frontend::lexer::lex(trimmed);
    let mut parser = crate::frontend::parser::Parser::new(tokens);
    let expr = parser.expression().ok()?;
    if parser.peek().ty != TokenType::Eof {
        return None;
    }
    let transformed = transform_expr_reactivity(&expr, state_vars, &[]);
    Some(emit_expr(&transformed))
}

pub fn transform_script_reactivity(script_str: &str, state_vars: &[String]) -> Option<String> {
    let tokens = crate::frontend::lexer::lex(script_str);
    let mut parser = crate::frontend::parser::Parser::new(tokens);
    let stmts = parser.parse().ok()?;
    let transformed: Vec<Stmt> = stmts
        .iter()
        .map(|s| transform_stmt_reactivity(s, state_vars, &[]))
        .collect();
    Some(transpile_to_js(&transformed))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::frontend::lexer::lex;
    use crate::frontend::parser::Parser;

    fn parse_and_transpile(src: &str) -> String {
        let tokens = lex(src);
        let mut parser = Parser::new(tokens);
        let stmts = parser.parse().expect("Parsing failed");
        transpile_to_js(&stmts)
    }

    #[test]
    fn test_transpile_types_erased() {
        let src = r#"
            type ID = int | string;
            let id: ID = 42;
            let name: string = "Eronom";
        "#;
        let js = parse_and_transpile(src);
        assert!(!js.contains("type ID"));
        assert!(js.contains("let id = 42;"));
        assert!(js.contains("let name = \"Eronom\";"));
    }

    #[test]
    fn test_transpile_enum() {
        let src = r#"
            enum Status {
                Pending,
                Active,
                Completed
            }
        "#;
        let js = parse_and_transpile(src);
        assert!(js.contains("const Status = Object.freeze({"));
        assert!(js.contains("Pending: 0,"));
        assert!(js.contains("Active: 1,"));
        assert!(js.contains("Completed: 2,"));
        assert!(js.contains("[0]: \"Pending\","));
    }

    #[test]
    fn test_transpile_struct_to_class() {
        let src = r#"
            struct Person {
                name: string,
                age: int,

                fn greet() {
                    return "Hello " + this.name;
                }
            }
        "#;
        let js = parse_and_transpile(src);
        assert!(js.contains("class Person {"));
        assert!(js.contains("constructor(init = {}) {"));
        assert!(js.contains("Object.assign(this, init);"));
        assert!(js.contains("greet() {"));
        assert!(js.contains("return (\"Hello \" + this.name);"));
    }

    #[test]
    fn test_transpile_typecast_and_functions() {
        let src = r#"
            fn add(a: int, b: int): int {
                return (a + b) as int;
            }
            let res = add(10, 20);
        "#;
        let js = parse_and_transpile(src);
        assert!(js.contains("function add(a, b) {"));
        assert!(js.contains("return (a + b);"));
        assert!(js.contains("let res = add(10, 20);"));
    }

    #[test]
    fn test_transpile_export() {
        let src = r#"
            export fn multiply(x: int, y: int): int {
                return x * y;
            }
        "#;
        let js = parse_and_transpile(src);
        assert!(js.contains("export function multiply(x, y) {"));
    }

    #[test]
    fn test_ast_reactivity_expr_basic() {
        let state_vars = vec!["count".to_string()];
        let res = transpile_expr_reactivity("count + 1", &state_vars).unwrap();
        assert_eq!(res, "(count.value + 1)");
    }

    #[test]
    fn test_ast_reactivity_string_literal_preservation() {
        let state_vars = vec!["count".to_string()];
        let res = transpile_expr_reactivity("\"The count is: \" + count", &state_vars).unwrap();
        assert_eq!(res, "(\"The count is: \" + count.value)");
    }

    #[test]
    fn test_ast_reactivity_object_key_preservation() {
        let state_vars = vec!["count".to_string()];
        let res = transpile_expr_reactivity("{ count: 10, other: count }", &state_vars).unwrap();
        assert_eq!(res, "{ count: 10, other: count.value }");
    }

    #[test]
    fn test_ast_reactivity_arrow_function_shadowing() {
        let state_vars = vec!["count".to_string()];
        let res = transpile_expr_reactivity("(count) => count + 1", &state_vars).unwrap();
        assert!(res.contains("(count) => {"));
        assert!(res.contains("return (count + 1);"));
    }

    #[test]
    fn test_ast_reactivity_no_double_value() {
        let state_vars = vec!["count".to_string()];
        let res = transpile_expr_reactivity("count.value + 1", &state_vars).unwrap();
        assert_eq!(res, "(count.value + 1)");
    }
}
