use crate::frontend::ast::{Expr, LiteralValue, Stmt};
use crate::frontend::token::TokenType;

pub fn transpile_to_js(stmts: &[Stmt]) -> String {
    let mut js = String::new();
    js.push_str("// Generated by Eronom Transpiler\n\n");
    let indent = 0;
    for stmt in stmts {
        emit_stmt(&mut js, stmt, indent);
    }
    js
}

fn emit_indent(out: &mut String, indent: usize) {
    for _ in 0..indent {
        out.push_str("    ");
    }
}

fn emit_stmt(out: &mut String, stmt: &Stmt, indent: usize) {
    match stmt {
        Stmt::TypeAlias(_, _, _, _) | Stmt::Interface(_, _, _, _) => {
            // Type annotations and interfaces are completely erased in JavaScript output
        }
        Stmt::Enum(name, variants, _) => {
            emit_indent(out, indent);
            out.push_str(&format!("const {} = Object.freeze({{\n", name));
            let mut next_auto_val: f64 = 0.0;
            let mut computed_variants = Vec::new();

            for (v_name, v_val) in variants {
                let val_str = match v_val {
                    Some(LiteralValue::Number(n)) => {
                        next_auto_val = n + 1.0;
                        n.to_string()
                    }
                    Some(LiteralValue::String(s)) => {
                        serde_json::to_string(s).unwrap_or_else(|_| format!("\"{}\"", s))
                    }
                    Some(LiteralValue::Boolean(b)) => b.to_string(),
                    Some(LiteralValue::Null) => "null".to_string(),
                    None => {
                        let current = next_auto_val;
                        next_auto_val += 1.0;
                        current.to_string()
                    }
                };
                computed_variants.push((v_name.clone(), val_str));
            }

            for (v_name, v_val) in &computed_variants {
                emit_indent(out, indent + 1);
                out.push_str(&format!("{}: {},\n", v_name, v_val));
            }

            // Numeric reverse mapping
            for (v_name, v_val) in &computed_variants {
                if v_val.parse::<f64>().is_ok() {
                    emit_indent(out, indent + 1);
                    out.push_str(&format!("[{}]: \"{}\",\n", v_val, v_name));
                }
            }

            emit_indent(out, indent);
            out.push_str("});\n\n");
        }
        Stmt::Struct(name, composed, _fields, methods, _) => {
            emit_indent(out, indent);
            let extends_clause = if let Some(parent) = composed.first() {
                format!(" extends {}", parent)
            } else {
                String::new()
            };
            out.push_str(&format!("class {}{} {{\n", name, extends_clause));

            // Constructor
            emit_indent(out, indent + 1);
            out.push_str("constructor(init = {}) {\n");
            if !composed.is_empty() {
                emit_indent(out, indent + 2);
                out.push_str("super(init);\n");
            }
            emit_indent(out, indent + 2);
            out.push_str("Object.assign(this, init);\n");
            emit_indent(out, indent + 1);
            out.push_str("}\n");

            // Methods
            for (m_name, m_params, m_body) in methods {
                emit_indent(out, indent + 1);
                out.push_str(&format!("{}({}) ", m_name, m_params.join(", ")));
                emit_stmt_inline(out, m_body, indent + 1);
                out.push('\n');
            }

            emit_indent(out, indent);
            out.push_str("}\n\n");
        }
        Stmt::VarDecl(name, _, is_const, expr, _) => {
            // Check if it's a top-level named function declaration: fn name(...) { ... }
            if let Expr::Function(params, _, body) = expr {
                emit_indent(out, indent);
                let param_names: Vec<&str> = params.iter().map(|p| p.name.as_str()).collect();
                out.push_str(&format!("function {}({}) ", name, param_names.join(", ")));
                emit_stmt_inline(out, body, indent);
                out.push('\n');
                return;
            }

            emit_indent(out, indent);
            let kw = if *is_const { "const" } else { "let" };
            out.push_str(&format!("{} {} = {};\n", kw, name, emit_expr(expr)));
        }
        Stmt::Expr(expr) => {
            emit_indent(out, indent);
            out.push_str(&format!("{};\n", emit_expr(expr)));
        }
        Stmt::Print(expr) => {
            emit_indent(out, indent);
            out.push_str(&format!("console.log({});\n", emit_expr(expr)));
        }
        Stmt::Block(stmts) => {
            emit_indent(out, indent);
            out.push_str("{\n");
            for s in stmts {
                emit_stmt(out, s, indent + 1);
            }
            emit_indent(out, indent);
            out.push_str("}\n");
        }
        Stmt::If(cond, then_b, else_b) => {
            emit_indent(out, indent);
            out.push_str(&format!("if ({}) ", emit_expr(cond)));
            emit_stmt_inline(out, then_b, indent);
            if let Some(else_stmt) = else_b {
                out.push_str(" else ");
                emit_stmt_inline(out, else_stmt, indent);
            }
            out.push('\n');
        }
        Stmt::While(cond, body) => {
            emit_indent(out, indent);
            out.push_str(&format!("while ({}) ", emit_expr(cond)));
            emit_stmt_inline(out, body, indent);
            out.push('\n');
        }
        Stmt::For(var_name, start, end, body) => {
            emit_indent(out, indent);
            out.push_str(&format!(
                "for (let {} = {}; {} <= {}; {}++) ",
                var_name,
                emit_expr(start),
                var_name,
                emit_expr(end),
                var_name
            ));
            emit_stmt_inline(out, body, indent);
            out.push('\n');
        }
        Stmt::ForIn(var_name, iter, body) => {
            emit_indent(out, indent);
            out.push_str(&format!("for (const {} of {}) ", var_name, emit_expr(iter)));
            emit_stmt_inline(out, body, indent);
            out.push('\n');
        }
        Stmt::Break => {
            emit_indent(out, indent);
            out.push_str("break;\n");
        }
        Stmt::Continue => {
            emit_indent(out, indent);
            out.push_str("continue;\n");
        }
        Stmt::Throw(expr) => {
            emit_indent(out, indent);
            out.push_str(&format!("throw {};\n", emit_expr(expr)));
        }
        Stmt::Try(try_body, catch_clause, finally_body) => {
            emit_indent(out, indent);
            out.push_str("try ");
            emit_stmt_inline(out, try_body, indent);
            if let Some((param, catch_b)) = catch_clause {
                out.push_str(&format!(" catch ({}) ", param));
                emit_stmt_inline(out, catch_b, indent);
            }
            if let Some(finally_b) = finally_body {
                out.push_str(" finally ");
                emit_stmt_inline(out, finally_b, indent);
            }
            out.push('\n');
        }
        Stmt::Return(expr_opt, _) => {
            emit_indent(out, indent);
            if let Some(e) = expr_opt {
                out.push_str(&format!("return {};\n", emit_expr(e)));
            } else {
                out.push_str("return;\n");
            }
        }
        Stmt::Switch(target, cases, default_body) => {
            emit_indent(out, indent);
            out.push_str(&format!("switch ({}) {{\n", emit_expr(target)));
            for case in cases {
                for v in &case.values {
                    emit_indent(out, indent + 1);
                    out.push_str(&format!("case {}:\n", emit_expr(v)));
                }
                emit_stmt(out, &case.body, indent + 2);
                emit_indent(out, indent + 2);
                out.push_str("break;\n");
            }
            if let Some(def) = default_body {
                emit_indent(out, indent + 1);
                out.push_str("default:\n");
                emit_stmt(out, def, indent + 2);
            }
            emit_indent(out, indent);
            out.push_str("}\n");
        }
        Stmt::Import(names, path) => {
            emit_indent(out, indent);
            let js_path = if path.ends_with(".er") {
                format!("{}.js", &path[..path.len() - 3])
            } else {
                path.clone()
            };
            out.push_str(&format!(
                "import {{ {} }} from \"{}\";\n",
                names.join(", "),
                js_path
            ));
        }
        Stmt::Export(inner) => {
            emit_indent(out, indent);
            out.push_str("export ");
            let mut inner_str = String::new();
            emit_stmt(&mut inner_str, inner, 0);
            out.push_str(inner_str.trim_start());
        }
        Stmt::Concurrent(body) => {
            emit_stmt(out, body, indent);
        }
    }
}

fn emit_stmt_inline(out: &mut String, stmt: &Stmt, indent: usize) {
    match stmt {
        Stmt::Block(stmts) => {
            out.push_str("{\n");
            for s in stmts {
                emit_stmt(out, s, indent + 1);
            }
            emit_indent(out, indent);
            out.push('}');
        }
        other => {
            out.push_str("{\n");
            emit_stmt(out, other, indent + 1);
            emit_indent(out, indent);
            out.push('}');
        }
    }
}

pub fn emit_expr(expr: &Expr) -> String {
    match expr {
        Expr::Literal(val) => match val {
            LiteralValue::Number(n) => n.to_string(),
            LiteralValue::String(s) => serde_json::to_string(s).unwrap_or_else(|_| format!("\"{}\"", s)),
            LiteralValue::Boolean(b) => b.to_string(),
            LiteralValue::Null => "null".to_string(),
        },
        Expr::Variable(name, _) => name.clone(),
        Expr::Assign(name, val, _) => format!("({} = {})", name, emit_expr(val)),
        Expr::Binary(left, op, right) => {
            let op_str = match op {
                TokenType::Plus => "+",
                TokenType::Minus => "-",
                TokenType::Star => "*",
                TokenType::Slash => "/",
                TokenType::Percent => "%",
                TokenType::EqualEqual => "===",
                TokenType::BangEqual => "!==",
                TokenType::Less => "<",
                TokenType::LessEqual => "<=",
                TokenType::Greater => ">",
                TokenType::GreaterEqual => ">=",
                TokenType::Ampersand => "&",
                TokenType::Pipe => "|",
                TokenType::Caret => "^",
                TokenType::LessLess => "<<",
                TokenType::GreaterGreater => ">>",
                _ => "+",
            };
            format!("({} {} {})", emit_expr(left), op_str, emit_expr(right))
        }
        Expr::Logical(left, op, right) => {
            let op_str = match op {
                TokenType::And => "&&",
                TokenType::Or => "||",
                _ => "&&",
            };
            format!("({} {} {})", emit_expr(left), op_str, emit_expr(right))
        }
        Expr::Unary(op, operand) => {
            let op_str = match op {
                TokenType::Bang => "!",
                TokenType::Minus => "-",
                TokenType::Typeof => "typeof ",
                TokenType::Tilde => "~",
                _ => "",
            };
            format!("({}{})", op_str, emit_expr(operand))
        }
        Expr::Prefix(op, operand) => {
            let op_str = match op {
                TokenType::PlusPlus => "++",
                TokenType::MinusMinus => "--",
                _ => "",
            };
            format!("({}{})", op_str, emit_expr(operand))
        }
        Expr::Postfix(op, operand) => {
            let op_str = match op {
                TokenType::PlusPlus => "++",
                TokenType::MinusMinus => "--",
                _ => "",
            };
            format!("({}{})", emit_expr(operand), op_str)
        }
        Expr::Ternary(cond, then_b, else_b) => {
            format!(
                "({} ? {} : {})",
                emit_expr(cond),
                emit_expr(then_b),
                emit_expr(else_b)
            )
        }
        Expr::Call(callee, args) => {
            let args_str = args.iter().map(emit_expr).collect::<Vec<_>>().join(", ");
            if let Expr::Variable(name, _) = &**callee {
                if name == "print" {
                    return format!("console.log({})", args_str);
                }
            }
            format!("{}({})", emit_expr(callee), args_str)
        }
        Expr::Get(obj, prop) => format!("{}.{}", emit_expr(obj), prop),
        Expr::Set(obj, prop, val) => format!("({}.{} = {})", emit_expr(obj), prop, emit_expr(val)),
        Expr::Array(items) => {
            let items_str = items.iter().map(emit_expr).collect::<Vec<_>>().join(", ");
            format!("[{}]", items_str)
        }
        Expr::Object(pairs) => {
            let pairs_str = pairs
                .iter()
                .map(|(k, v)| format!("{}: {}", k, emit_expr(v)))
                .collect::<Vec<_>>()
                .join(", ");
            format!("{{ {} }}", pairs_str)
        }
        Expr::Function(params, _, body) => {
            let param_names: Vec<&str> = params.iter().map(|p| p.name.as_str()).collect();
            let mut body_str = String::new();
            emit_stmt_inline(&mut body_str, body, 0);
            format!("({}) => {}", param_names.join(", "), body_str)
        }
        Expr::GetIndex(obj, idx) => format!("{}[{}]", emit_expr(obj), emit_expr(idx)),
        Expr::SetIndex(obj, idx, val) => {
            format!("({}[{}] = {})", emit_expr(obj), emit_expr(idx), emit_expr(val))
        }
        Expr::StructInst(name, pairs, _) => {
            let pairs_str = pairs
                .iter()
                .map(|(k, v)| format!("{}: {}", k, emit_expr(v)))
                .collect::<Vec<_>>()
                .join(", ");
            format!("new {}({{ {} }})", name, pairs_str)
        }
        Expr::TypeCast(inner, _, _) => emit_expr(inner),
        Expr::Spawn(inner) => format!("Promise.resolve().then(() => {})", emit_expr(inner)),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::frontend::lexer::lex;
    use crate::frontend::parser::Parser;

    fn parse_and_transpile(src: &str) -> String {
        let tokens = lex(src);
        let mut parser = Parser::new(tokens);
        let stmts = parser.parse().expect("Parsing failed");
        transpile_to_js(&stmts)
    }

    #[test]
    fn test_transpile_types_erased() {
        let src = r#"
            type ID = int | string;
            let id: ID = 42;
            let name: string = "Eronom";
        "#;
        let js = parse_and_transpile(src);
        assert!(!js.contains("type ID"));
        assert!(js.contains("let id = 42;"));
        assert!(js.contains("let name = \"Eronom\";"));
    }

    #[test]
    fn test_transpile_enum() {
        let src = r#"
            enum Status {
                Pending,
                Active,
                Completed
            }
        "#;
        let js = parse_and_transpile(src);
        assert!(js.contains("const Status = Object.freeze({"));
        assert!(js.contains("Pending: 0,"));
        assert!(js.contains("Active: 1,"));
        assert!(js.contains("Completed: 2,"));
        assert!(js.contains("[0]: \"Pending\","));
    }

    #[test]
    fn test_transpile_struct_to_class() {
        let src = r#"
            struct Person {
                name: string,
                age: int,

                fn greet() {
                    return "Hello " + this.name;
                }
            }
        "#;
        let js = parse_and_transpile(src);
        assert!(js.contains("class Person {"));
        assert!(js.contains("constructor(init = {}) {"));
        assert!(js.contains("Object.assign(this, init);"));
        assert!(js.contains("greet() {"));
        assert!(js.contains("return (\"Hello \" + this.name);"));
    }

    #[test]
    fn test_transpile_typecast_and_functions() {
        let src = r#"
            fn add(a: int, b: int): int {
                return (a + b) as int;
            }
            let res = add(10, 20);
        "#;
        let js = parse_and_transpile(src);
        assert!(js.contains("function add(a, b) {"));
        assert!(js.contains("return (a + b);"));
        assert!(js.contains("let res = add(10, 20);"));
    }

    #[test]
    fn test_transpile_export() {
        let src = r#"
            export fn multiply(x: int, y: int): int {
                return x * y;
            }
        "#;
        let js = parse_and_transpile(src);
        assert!(js.contains("export function multiply(x, y) {"));
    }
}
